package smartcampus;
import java.awt.*; import java.awt.event.*; import java.sql.*;
public class Dashboard extends Frame {
 CardLayout cards=new CardLayout(); Panel content=new Panel(cards); Label status=new Label("Ready");
 public Dashboard(){super("Smart Campus Parking Intelligence — AWT");setSize(1280,780);setLayout(new BorderLayout());setBackground(UI.BG);
  Panel side=new Panel(new GridLayout(0,1,5,5));side.setBackground(UI.NAVY);side.setPreferredSize(new Dimension(205,0));
  String[] names={"DASHBOARD","PARKING MAP","RESERVATIONS","ENTRY / EXIT","USERS","VEHICLES","PASSES","VIOLATIONS","REPORTS","SETTINGS"};
  Component[] views={new Home(this),new ParkingMap(this),new Reservation(this),new Session(this),new Users(this),new Vehicles(this),new Pass(this),new Violation(this),new Reports(this),new Settings(this)};
  for(int i=0;i<names.length;i++){final int x=i;Button b=UI.button(names[i],i==0?UI.CYAN:UI.WHITE);side.add(b);content.add(views[i],names[i]);b.addActionListener(e->{cards.show(content,names[x]);status.setText(names[x]+" loaded");});}
  add(side,BorderLayout.WEST);add(content,BorderLayout.CENTER);Panel bottom=new Panel(new BorderLayout());bottom.setBackground(UI.NAVY);status.setForeground(Color.WHITE);bottom.add(status,BorderLayout.WEST);bottom.add(UI.label("AWT • JDBC • MYSQL",12,UI.CYAN),BorderLayout.EAST);add(bottom,BorderLayout.SOUTH);setLocationRelativeTo(null);addWindowListener(new WindowAdapter(){public void windowClosing(WindowEvent e){System.exit(0);}});setVisible(true);}
}
class Home extends Panel{
 Dashboard d; Label total=UI.label("0",28,UI.CYAN),free=UI.label("0",28,UI.GREEN),occ=UI.label("0",28,UI.ORANGE),util=UI.label("0%",28,UI.PURPLE),traffic=UI.label("0",28,UI.RED),pred=UI.label("0%",28,UI.CYAN); TextArea alerts=new TextArea();
 Home(Dashboard d){this.d=d;setLayout(new BorderLayout(12,12));setBackground(UI.BG);Panel head=new Panel(new BorderLayout());head.setBackground(UI.BG);head.add(UI.label("INTELLIGENT PARKING COMMAND CENTER",24,UI.NAVY),BorderLayout.WEST);Button r=UI.button("REFRESH",UI.CYAN);head.add(r,BorderLayout.EAST);add(head,BorderLayout.NORTH);
  Panel grid=new Panel(new GridLayout(2,3,12,12));grid.add(tile("TOTAL SLOTS",total,UI.CARD));grid.add(tile("AVAILABLE",free,UI.CARD));grid.add(tile("OCCUPIED",occ,UI.CARD));grid.add(tile("UTILIZATION",util,UI.CARD));grid.add(tile("TRAFFIC LEVEL",traffic,UI.CARD));grid.add(tile("PREDICTED OCCUPANCY",pred,UI.CARD));add(grid,BorderLayout.CENTER);
  alerts.setEditable(false);alerts.setBackground(Color.WHITE);Panel a=new Panel(new BorderLayout());a.add(UI.label("LIVE ALERTS",16,UI.RED),BorderLayout.NORTH);a.add(alerts,BorderLayout.CENTER);a.setPreferredSize(new Dimension(0,150));add(a,BorderLayout.SOUTH);r.addActionListener(e->load());load();}
 Panel tile(String name,Label value,Color bg){Panel p=UI.card(180,110);p.setBackground(bg);p.setLayout(new BorderLayout());p.add(UI.label(name,13,Color.WHITE),BorderLayout.NORTH);p.add(value,BorderLayout.CENTER);return p;}
 void load(){try(Connection c=DB.get()){ResultSet r=c.createStatement().executeQuery("select count(*) total,sum(status='Available') free,sum(status='Occupied') occ from parking_slots");if(r.next()){int t=r.getInt(1),f=r.getInt(2),o=r.getInt(3);total.setText(""+t);free.setText(""+f);occ.setText(""+o);util.setText(t==0?"0%":(o*100/t)+"%");}r=c.createStatement().executeQuery("select coalesce(round(avg(congestion_level),0),0) from traffic_records where record_time>=now()-interval 1 day");if(r.next())traffic.setText(r.getString(1)+" / 100");r=c.createStatement().executeQuery("select coalesce(round(avg(occupied_slots/total_slots*100),0),0) from occupancy_records where recorded_at>=now()-interval 7 day");if(r.next())pred.setText(r.getString(1)+"%");r=c.createStatement().executeQuery("select message from alerts where is_read=0 order by created_at desc limit 8");StringBuilder s=new StringBuilder();while(r.next())s.append("• ").append(r.getString(1)).append("\n");alerts.setText(s.length()==0?"No active alerts":s.toString());}catch(Exception e){alerts.setText("Database not connected: "+e.getMessage());}}
}
