package smartcampus;
import java.awt.*;import java.awt.event.*;import java.sql.*;
public class ParkingMap extends Panel{
 MapCanvas map=new MapCanvas(); Label rec=UI.label("SMART RECOMMENDATION: —",15,UI.NAVY); Choice vehicle=new Choice(); Button recommend=UI.button("FIND BEST SLOT",UI.GREEN);
 ParkingMap(Frame owner){setLayout(new BorderLayout(8,8));setBackground(UI.BG);Panel top=new Panel(new BorderLayout());top.setBackground(UI.BG);top.add(UI.label("INTERACTIVE PARKING MAP",22,UI.NAVY),BorderLayout.WEST);Panel r=new Panel();r.add(new Label("Vehicle:"));r.add(vehicle);r.add(recommend);top.add(r,BorderLayout.EAST);add(top,BorderLayout.NORTH);add(map,BorderLayout.CENTER);add(rec,BorderLayout.SOUTH);loadVehicles();recommend.addActionListener(e->recommend());}
 void loadVehicles(){try(Connection c=DB.get()){ResultSet r=c.createStatement().executeQuery("select plate_number from vehicles order by plate_number");while(r.next())vehicle.add(r.getString(1));}catch(Exception e){}}
 void recommend(){try(Connection c=DB.get();PreparedStatement p=c.prepareStatement("select s.slot_id,s.slot_code,z.zone_name,z.distance_meters from parking_slots s join parking_zones z on s.zone_id=z.zone_id where s.status='Available' order by z.distance_meters, s.slot_id limit 1")){ResultSet r=p.executeQuery();if(r.next()){rec.setText("BEST SLOT: "+r.getString("slot_code")+" • "+r.getString("zone_name")+" • "+r.getInt("distance_meters")+"m walking distance");}}catch(Exception e){rec.setText("Recommendation unavailable: "+e.getMessage());}}
 class MapCanvas extends Canvas{MapCanvas(){setBackground(Color.WHITE);addMouseListener(new MouseAdapter(){public void mouseClicked(MouseEvent e){}});}public void paint(Graphics g){super.paint(g);try(Connection c=DB.get()){ResultSet r=c.createStatement().executeQuery("select slot_code,status from parking_slots order by slot_id");int i=0;while(r.next()){int x=30+(i%8)*115,y=30+(i/8)*90;Color col=r.getString(2).equals("Available")?UI.GREEN:r.getString(2).equals("Occupied")?UI.RED:UI.ORANGE;g.setColor(col);g.fillRoundRect(x,y,95,60,14,14);g.setColor(Color.BLACK);g.setFont(new Font("SansSerif",Font.BOLD,13));g.drawString(r.getString(1),x+25,y+28);g.setFont(new Font("SansSerif",Font.PLAIN,10));g.drawString(r.getString(2),x+18,y+45);i++;}}catch(Exception e){g.setColor(UI.RED);g.drawString("Database connection required",30,40);}}}
}
